image: node:6

stages:
  - build
  - validate and store config
  - deploy
  - test
  - staging
  - production

# WARNING: check if your tenant is case sensitive (default) to input vars below
variables:
  CONFIG_DIR: ""
  # ex: CONFIG_DIR: "./conf"
  SWEAGLE_SCRIPTS_DIR: "./scripts"
  # ex: SWEAGLE_SCRIPTS_DIR: "./scripts"
  SWEAGLE_PATH: ""
  # ex: SWEAGLE_PATH: "dimension,node1,node2"
  SWEAGLE_MDS: ""
  # ex: SWEAGLE_MDS: "dimension" or SWEAGLE_MDS:$APP_NAME-$ENV_NAME (if they have been defined before)
  #SWEAGLE_VALIDATORS: "noDevValues noEmptyValues passwordChecker"
  SWEAGLE_VALIDATORS: ""
  # ex: SWEAGLE_VALIDATORS: "noDevValues noEmptyValues passwordChecker"
  SWEAGLE_EXPORTER: ""
  # ex: SWEAGLE_EXPORTER: "all" or SWEAGLE_EXPORTER: "returnDataForNodeName"
  SWEAGLE_EXPORTER_ARGS: ""
  # ex: SWEAGLE_EXPORTER_ARGS: "" or SWEAGLE_EXPORTER_ARGS: "node1"
  SWEAGLE_EXPORTER_FORMAT: ""
  # ex: SWEAGLE_EXPORTER_FORMAT: "YAML"
  SWEAGLE_EXPORTER_OUTPUT: ""
  # ex: SWEAGLE_EXPORTER_OUTPUT: ""
  GITLAB_TARGET_DIR: "/release"
  # ex: GITLAB_TARGET_DIR: "/release"

#build:
#  stage: build
#  before_script: []
#  script:
#    - echo build
#  after_script: []

# At the end of build, upload "builded" configuration to SWEAGLE
uploadConfiguration:
  stage: build
  only:
  - master
  script:
    - echo **********
    - echo *** Send configuration to SWEAGLE
    - chmod +x $SWEAGLE_SCRIPTS_DIR/*.sh
    - $SWEAGLE_SCRIPTS_DIR/uploadDirToSweagle.sh $SWEAGLE_PATH $CONFIG_DIR
    - echo *** Configuration sent
  when: on_success
  # possible values always, on_success, on_failure, manual

getConfig:
  stage: validate and store config
  only:
  - master
  variables:
    # specific variables for this step
  before_script:
    - echo **********
    - echo *** Check configuration from SWEAGLE
    - chmod +x $SWEAGLE_SCRIPTS_DIR/*.sh
    - $SWEAGLE_SCRIPTS_DIR/checkAllConfigByMdsValidator.sh $SWEAGLE_MDS $SWEAGLE_VALIDATORS
    # you may create your own wrapper of Sweagle scripts to match an App or Env to an MDS
    - echo *** Retrieve lastest valid configuration from SWEAGLE
    - echo *** SWEAGLE will also fill token values, if any
    # Store your config snapshot in order to be able to retrieve it
    - $SWEAGLE_SCRIPTS_DIR/storeConfigSnapshotByMds.sh $SWEAGLE_MDS
  script:
    # Download your config using exporter
    - $SWEAGLE_SCRIPTS_DIR/getConfigByMdsParserArgs.sh $SWEAGLE_MDS $SWEAGLE_EXPORTER args=$SWEAGLE_EXPORTER_ARGS format=$SWEAGLE_EXPORTER_FORMAT output=$SWEAGLE_EXPORTER_OUTPUT
    # Store config back in Gitlab repository
    #- $SWEAGLE_SCRIPTS_DIR/StoreFileInGitlab.sh $SWEAGLE_EXPORTER_OUTPUT $GITLAB_TARGET_DIR
  artifacts:
    # Store config in GitLab Artifact
    paths:
    - $SWEAGLE_EXPORTER_OUTPUT
  when: on_success
  # possible values always, on_success, on_failure, manual

deployTestEnvironment:
  stage: deploy
  only:
  - master
  variables:
    # specific variables for this step
  script:
    - echo deploy TEST environment
    - echo upload deployed config to SWEAGLE
    # Store deployed config back in SWEAGLE (file is taken from artifacts)
    - chmod +x $SWEAGLE_SCRIPTS_DIR/*.sh
    - $SWEAGLE_SCRIPTS_DIR/uploadFileToSweagle.sh $SWEAGLE_PATH,deployed $SWEAGLE_EXPORTER_OUTPUT
  when: on_success
  # possible values always, on_success, on_failure, manual

#staging:
#  stage: staging
#  only:
#    - release
#  before_script: [Use Sweagle again]
#  script:
#    - echo deploy to staging


#production:
#  stage: production
#  before_script: [Use Sweagle again]
#  script:
#    - echo deploy to production
#  when: manual
